[project]
name = "databases"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "mysql-connector-python>=9.5.0",
    "psycopg[binary]>=3.2.10",
    "pydantic>=2.11.9",
    "python-tds>=1.15.0",
]
